export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST"

export const REMOVE_FROM_PLAYLIST = "REMOVE_FROM_PLAYLIST"

export const CLEAR_PLAYLIST = "CLEAR_PLAYLIST"

export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK"