const actionTypes = {
  ADD_VIDEO: "ADD_VIDEO",
  VALIDATE_URL: "VALIDATE_URL",
  REMOVE_VIDEO: "REMOVE_VIDEO",
  MOVE_UP: "MOVE_UP",
  MOVE_DOWN: "MOVE_DOWN",
  VIDEO_ERROR: "VIDEO_ERROR",
  ADD_PLAYLIST: "ADD_PLAYLIST"
};

export default actionTypes;
